langauge: ruby
sudo: false
cache: bundler

branches:
  only: master

before_install:
  - rvm install 2.0.0
  - rvm install 2.1.5
  - rvm install 2.2.1
  - rvm install jruby-1.7.19

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - jruby-1.7.19

matrix:
  fast_finish: true
