langauge: ruby
sudo: false
cache: bundler

branches:
  only: master

# make other rubies available for switching
before_install:
  - rvm install 2.0.0
  - rvm install 2.1.5
  - rvm install jruby-1.7.25

rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.4
  - 2.3.1
  - jruby-1.7.25

matrix:
  fast_finish: true
